# Generated by Django 4.1.7 on 2023-05-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collecte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointdecollecte',
            name='stock_casier',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
    ]
